version: "3.9"
services:
  mysql:
    image: mysql:8
    command: --init-file /docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "safe_size_db"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 25s
      retries: 3
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql-data:/var/lib/mysql/
    ports:
      - "3306:3306"
  api:
    build: .
    command:
      - "/bin/sh"
      - "-c"
      - "make build && /safe-size-pay/safe-size-pay"
    ports:
      - "8080:8080"
    environment:
      MYSQL_DSN: root:password@tcp(mysql:3306)/safe_size_db?parseTime=true&sql_mode=NO_ZERO_DATE
    volumes:
      - .:/safe-size-pay
    depends_on:
      - mysql

volumes:
    mysql-data:
networks:
  default:
    name: safe-size-pay-stack
    driver: overlay
    attachable: true